name: TriggeredEmailer CI/CD

on:
  push:
    branches:
      - devops/setup-ci-cd-pipeline

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: published_app
          path: ./publish
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: published_app
          path: ./TriggeredEmailer/publish/
      - name: Copy file via scp password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          source: "./TriggeredEmailer/publish/*"
          target: "C:/inetpub/wwwroot/triggered_emailer_artifact"
          strip_components: 2

      - name: SSH into VM and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          script: powershell -File "C:\inetpub\wwwroot\triggered_emailer_deployment_script.ps1"
          